{
 "title": "MeasureX",
 "time": { "from": "2025-10-16T07:44:10.393Z", "to": "2025-10-16T10:16:01.934Z" },
 "panels": [
  {
   "title": "Throughput Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "collection": "measurements",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n        \"$expr\": {\n            \"$and\": [\n              {\n                \"$gt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {\n                \"$gt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {\n                \"$lt\": [\"$start_time\", \"$stop_time\"]\n              },\n              {  \n                \"$eq\": [\"$type\", \"iperf\"]\n              }\n            ]\n        }\n    }\n  },\n  {\n    \"$lookup\": {\n        \"from\": \"results\",\n        \"localField\": \"results\",\n        \"foreignField\": \"_id\",\n        \"as\": \"resultsData\"\n    }\n  },\n  {\n    \"$unwind\": \"$resultsData\"\n  },\n  {\n    \"$project\": {\n        \"_id\": 0,\n        \"time\": {\"$toDate\": {\"$multiply\": [\"$start_time\", 1000]}},\n        \"avg_speed\": \"$resultsData.avg_speed\"\n    }\n  },\n  {\n    \"$sort\": {\"time\": 1}\n  }\n]"
    }
   ]
  },
  {
   "title": "Latency Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "measurements",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n        \"$expr\": {\n            \"$and\": [\n              {\n                \"$gt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {\n                \"$gt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {\n                \"$lt\": [\"$start_time\", \"$stop_time\"]\n              },\n              { \n                \"$eq\": [\"$type\", \"ping\"]\n              }\n            ]\n        }\n    }\n  },\n  {\n    \"$lookup\": {\n        \"from\": \"results\",\n        \"localField\": \"results\",\n        \"foreignField\": \"_id\",\n        \"as\": \"resultsData\"\n    }\n  },\n  {\n    \"$unwind\": \"$resultsData\"\n  },\n  {\n    \"$project\": {\n        \"_id\": 0,\n        \"time\": {\"$toDate\": {\"$multiply\": [\"$start_time\", 1000]}},\n        \"rtt_avg\": \"$resultsData.rtt_avg\"\n    }\n  },\n  {\n    \"$sort\": {\"time\": 1}\n  }\n]"
    }
   ]
  },
  {
   "title": "AoI Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "measurements",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n        \"$expr\": {\n            \"$and\": [\n              {\n                \"$gt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$start_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {\n                \"$gt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__from\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$stop_time\", {\"$divide\": [{ \"$toLong\": \"$__to\" },1000]}]\n              },\n              {  \n                \"$lt\": [\"$start_time\", \"$stop_time\"]\n              },\n              {\n                \"$eq\": [\"$type\", \"aoi\"]\n              }\n            ]\n        }\n    }\n  },\n  {\n    \"$lookup\": {\n        \"from\": \"results\",\n        \"localField\": \"results\",\n        \"foreignField\": \"_id\",\n        \"as\": \"resultsData\"\n    }\n  },\n  {\n    \"$unwind\": \"$resultsData\"\n  },\n  {\n    \"$project\": {\n        \"_id\": 0,\n        \"time\": {\"$toDate\": {\"$multiply\": [\"$start_time\", 1000]}},\n        \"max_aoi\": \"$resultsData.max\"\n    }\n  },\n  {\n    \"$sort\": {\"time\": 1}\n  }\n]"
    }
   ]
  }
 ]
}