{
 "title": "MeasureX",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$and\": [\n        { \"type\": \"iperf\" },\n        {\n          \"$expr\": {\n            \"$and\": [\n              {\n                \"$gte\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__from\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              },\n              {\n                \"$lt\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__to\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              }\n            ]\n          }\n        }\n      ]\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": \"$timestamp_iso\",  \n      \"avg_speed\": 1\n    }\n  },\n  {\n    \"$sort\": { \"time\": 1 }\n  }\n]"
    }
   ]
  },
  {
   "title": "Latency Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$and\": [\n        { \"type\": \"ping\" },\n        {\n          \"$expr\": {\n            \"$and\": [\n              {\n                \"$gte\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__from\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              },\n              {\n                \"$lt\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__to\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              }\n            ]\n          }\n        }\n      ]\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": \"$timestamp_iso\",  \n      \"rtt_avg\": 1\n    }\n  },\n  {\n    \"$sort\": { \"time\": 1 }\n  }\n]"
    }
   ]
  },
  {
   "title": "AoI Measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "collection": "results",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"$and\": [\n        { \"type\": \"aoi\" },\n        {\n          \"$expr\": {\n            \"$and\": [\n              {\n                \"$gte\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__from\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              },\n              {\n                \"$lt\": [\n                  \"$timestamp_iso\",\n                  {\n                    \"$dateTrunc\": {\n                      \"date\": { \"$toDate\": { \"$toLong\": \"$__to\" } },\n                      \"unit\": \"second\"\n                    }\n                  }\n                ]\n              }\n            ]\n          }\n        }\n      ]\n    }\n  },\n  {\n    \"$project\": {\n      \"_id\": 0,\n      \"time\": \"$timestamp_iso\",  \n      \"aoi_max\": 1\n    }\n  },\n  {\n    \"$sort\": { \"time\": 1 }\n  }\n]"
    }
   ]
  }
 ]
}